export const FIND_MOVIES = 'FIND_MOVIES';
export const FIND_MOVIE = 'FIND_MOVIE'
export const USER_LOGEADO = 'USER_LOGEADO'
export const USER_DESLOGEADO = 'USER_DESLOGEADO'
export const ADD_FAVORITES = 'ADD_FAVORITES'
export const DELETE_FAVORITES = 'DELETE_FAVORITES'
export const SHOW_FAVORITES = 'SHOW_FAVORITES'